// internal/proto/shortener.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *SaveResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SaveBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*BatchRequest        `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBatchRequest) Reset() {
	*x = SaveBatchRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBatchRequest) ProtoMessage() {}

func (x *SaveBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBatchRequest.ProtoReflect.Descriptor instead.
func (*SaveBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *SaveBatchRequest) GetBatch() []*BatchRequest {
	if x != nil {
		return x.Batch
	}
	return nil
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type SaveBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         []*BatchResponse       `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveBatchResponse) Reset() {
	*x = SaveBatchResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBatchResponse) ProtoMessage() {}

func (x *SaveBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBatchResponse.ProtoReflect.Descriptor instead.
func (*SaveBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *SaveBatchResponse) GetBatch() []*BatchResponse {
	if x != nil {
		return x.Batch
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *BatchResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDResponse) Reset() {
	*x = GetByIDResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDResponse) ProtoMessage() {}

func (x *GetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetByIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetByIDResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetAllByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URL                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByUserIDResponse) Reset() {
	*x = GetAllByUserIDResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByUserIDResponse) ProtoMessage() {}

func (x *GetAllByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllByUserIDResponse) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_internal_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *URL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type DeleteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBatchRequest) Reset() {
	*x = DeleteBatchRequest{}
	mi := &file_internal_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchRequest) ProtoMessage() {}

func (x *DeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBatchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int64                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int64                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_internal_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *StatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_internal_proto_shortener_proto protoreflect.FileDescriptor

const file_internal_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/shortener.proto\x12\tshortener\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n" +
	"\vSaveRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"&\n" +
	"\fSaveResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"A\n" +
	"\x10SaveBatchRequest\x12-\n" +
	"\x05batch\x18\x01 \x03(\v2\x17.shortener.BatchRequestR\x05batch\"X\n" +
	"\fBatchRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"C\n" +
	"\x11SaveBatchResponse\x12.\n" +
	"\x05batch\x18\x01 \x03(\v2\x18.shortener.BatchResponseR\x05batch\"S\n" +
	"\rBatchResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x0fGetByIDResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"<\n" +
	"\x16GetAllByUserIDResponse\x12\"\n" +
	"\x04urls\x18\x01 \x03(\v2\x0e.shortener.URLR\x04urls\"E\n" +
	"\x03URL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"&\n" +
	"\x12DeleteBatchRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x03R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x03R\x05users2\xf4\x03\n" +
	"\x10ShortenerService\x129\n" +
	"\x04Save\x12\x16.shortener.SaveRequest\x1a\x17.shortener.SaveResponse\"\x00\x12H\n" +
	"\tSaveBatch\x12\x1b.shortener.SaveBatchRequest\x1a\x1c.shortener.SaveBatchResponse\"\x00\x12B\n" +
	"\aGetByID\x12\x19.shortener.GetByIDRequest\x1a\x1a.shortener.GetByIDResponse\"\x00\x12M\n" +
	"\x0eGetAllByUserID\x12\x16.google.protobuf.Empty\x1a!.shortener.GetAllByUserIDResponse\"\x00\x12N\n" +
	"\x13DeleteBatchByUserID\x12\x1d.shortener.DeleteBatchRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x18.shortener.StatsResponse\"\x00\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B8Z6github.com/IvanKondrashkov/go-shortener/internal/protob\x06proto3"

var (
	file_internal_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_proto_shortener_proto_rawDescData []byte
)

func file_internal_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_shortener_proto_rawDesc), len(file_internal_proto_shortener_proto_rawDesc)))
	})
	return file_internal_proto_shortener_proto_rawDescData
}

var file_internal_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_shortener_proto_goTypes = []any{
	(*SaveRequest)(nil),            // 0: shortener.SaveRequest
	(*SaveResponse)(nil),           // 1: shortener.SaveResponse
	(*SaveBatchRequest)(nil),       // 2: shortener.SaveBatchRequest
	(*BatchRequest)(nil),           // 3: shortener.BatchRequest
	(*SaveBatchResponse)(nil),      // 4: shortener.SaveBatchResponse
	(*BatchResponse)(nil),          // 5: shortener.BatchResponse
	(*GetByIDRequest)(nil),         // 6: shortener.GetByIDRequest
	(*GetByIDResponse)(nil),        // 7: shortener.GetByIDResponse
	(*GetAllByUserIDResponse)(nil), // 8: shortener.GetAllByUserIDResponse
	(*URL)(nil),                    // 9: shortener.URL
	(*DeleteBatchRequest)(nil),     // 10: shortener.DeleteBatchRequest
	(*StatsResponse)(nil),          // 11: shortener.StatsResponse
	(*emptypb.Empty)(nil),          // 12: google.protobuf.Empty
}
var file_internal_proto_shortener_proto_depIdxs = []int32{
	3,  // 0: shortener.SaveBatchRequest.batch:type_name -> shortener.BatchRequest
	5,  // 1: shortener.SaveBatchResponse.batch:type_name -> shortener.BatchResponse
	9,  // 2: shortener.GetAllByUserIDResponse.urls:type_name -> shortener.URL
	0,  // 3: shortener.ShortenerService.Save:input_type -> shortener.SaveRequest
	2,  // 4: shortener.ShortenerService.SaveBatch:input_type -> shortener.SaveBatchRequest
	6,  // 5: shortener.ShortenerService.GetByID:input_type -> shortener.GetByIDRequest
	12, // 6: shortener.ShortenerService.GetAllByUserID:input_type -> google.protobuf.Empty
	10, // 7: shortener.ShortenerService.DeleteBatchByUserID:input_type -> shortener.DeleteBatchRequest
	12, // 8: shortener.ShortenerService.GetStats:input_type -> google.protobuf.Empty
	12, // 9: shortener.ShortenerService.Ping:input_type -> google.protobuf.Empty
	1,  // 10: shortener.ShortenerService.Save:output_type -> shortener.SaveResponse
	4,  // 11: shortener.ShortenerService.SaveBatch:output_type -> shortener.SaveBatchResponse
	7,  // 12: shortener.ShortenerService.GetByID:output_type -> shortener.GetByIDResponse
	8,  // 13: shortener.ShortenerService.GetAllByUserID:output_type -> shortener.GetAllByUserIDResponse
	12, // 14: shortener.ShortenerService.DeleteBatchByUserID:output_type -> google.protobuf.Empty
	11, // 15: shortener.ShortenerService.GetStats:output_type -> shortener.StatsResponse
	12, // 16: shortener.ShortenerService.Ping:output_type -> google.protobuf.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_shortener_proto_init() }
func file_internal_proto_shortener_proto_init() {
	if File_internal_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_shortener_proto_rawDesc), len(file_internal_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_proto_shortener_proto = out.File
	file_internal_proto_shortener_proto_goTypes = nil
	file_internal_proto_shortener_proto_depIdxs = nil
}
