version: '2'
services:
  shortener-db:
    image: postgres:14-alpine
    container_name: shortener-db-ct
    volumes:
      - postgres_home:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d shortener" ]
      interval: 10s
      timeout: 2s
      retries: 2

volumes:
  postgres_home: